# config.yaml
train_data:
  - 'BTCUSDT-3m-2017-08.csv'
  - 'BTCUSDT-3m-2017-09.csv'
  - 'BTCUSDT-3m-2017-10.csv'
  - 'BTCUSDT-3m-2017-11.csv'
  - 'BTCUSDT-3m-2017-12.csv'
  - 'BTCUSDT-3m-2018-01.csv'
  - 'BTCUSDT-3m-2018-02.csv'
  - 'BTCUSDT-3m-2018-03.csv'
  - 'BTCUSDT-3m-2018-04.csv'
  - 'BTCUSDT-3m-2018-05.csv'
  - 'BTCUSDT-3m-2018-06.csv'
  - 'BTCUSDT-3m-2018-07.csv'

  - 'BTCUSDT-3m-2018-08.csv'
  - 'BTCUSDT-3m-2018-09.csv'
  - 'BTCUSDT-3m-2018-10.csv'
  - 'BTCUSDT-3m-2018-11.csv'
  - 'BTCUSDT-3m-2018-12.csv'
  - 'BTCUSDT-3m-2019-01.csv'
  - 'BTCUSDT-3m-2019-02.csv'
  - 'BTCUSDT-3m-2019-03.csv'
  - 'BTCUSDT-3m-2019-04.csv'
  - 'BTCUSDT-3m-2019-05.csv'
  - 'BTCUSDT-3m-2019-06.csv'
  - 'BTCUSDT-3m-2019-07.csv'
  - 'BTCUSDT-3m-2019-08.csv'
  - 'BTCUSDT-3m-2019-09.csv'
  - 'BTCUSDT-3m-2019-10.csv'
  - 'BTCUSDT-3m-2019-11.csv'
  - 'BTCUSDT-3m-2019-12.csv'
  - 'BTCUSDT-3m-2020-01.csv'
  - 'BTCUSDT-3m-2020-02.csv'
  - 'BTCUSDT-3m-2020-03.csv'
  - 'BTCUSDT-3m-2020-04.csv'
  - 'BTCUSDT-3m-2020-05.csv'
  - 'BTCUSDT-3m-2020-06.csv'
  - 'BTCUSDT-3m-2020-07.csv'
  - 'BTCUSDT-3m-2020-08.csv'
  - 'BTCUSDT-3m-2020-09.csv'
  - 'BTCUSDT-3m-2020-10.csv'
  - 'BTCUSDT-3m-2020-11.csv'
  - 'BTCUSDT-3m-2020-12.csv'
val_data:
  - 'BTCUSDT-3m-2021-01.csv'
  - 'BTCUSDT-3m-2021-02.csv'
  - 'BTCUSDT-3m-2021-03.csv'
  - 'BTCUSDT-3m-2021-04.csv'
  - 'BTCUSDT-3m-2021-05.csv'
  - 'BTCUSDT-3m-2021-06.csv'
  - 'BTCUSDT-3m-2021-07.csv'
  - 'BTCUSDT-3m-2021-08.csv'
  - 'BTCUSDT-3m-2021-09.csv'
  - 'BTCUSDT-3m-2021-10.csv'
  - 'BTCUSDT-3m-2021-11.csv'
  - 'BTCUSDT-3m-2021-12.csv'
  - 'BTCUSDT-3m-2022-01.csv'
  - 'BTCUSDT-3m-2022-02.csv'
  - 'BTCUSDT-3m-2022-03.csv'
  - 'BTCUSDT-3m-2022-04.csv'
  - 'BTCUSDT-3m-2022-05.csv'
  - 'BTCUSDT-3m-2022-06.csv'
  - 'BTCUSDT-3m-2022-07.csv'
  - 'BTCUSDT-3m-2022-08.csv'
  - 'BTCUSDT-3m-2022-09.csv'
  - 'BTCUSDT-3m-2022-10.csv'
  - 'BTCUSDT-3m-2022-11.csv'
  - 'BTCUSDT-3m-2022-12.csv'
test_data:
  - 'BTCUSDT-3m-2023-01.csv'
  - 'BTCUSDT-3m-2023-02.csv'
  - 'BTCUSDT-3m-2023-03.csv'
  - 'BTCUSDT-3m-2023-04.csv'
  - 'BTCUSDT-3m-2023-05.csv'
  - 'BTCUSDT-3m-2023-06.csv'
  - 'BTCUSDT-3m-2023-07.csv'
  - 'BTCUSDT-3m-2023-08.csv'
  - 'BTCUSDT-3m-2023-09.csv'
  - 'BTCUSDT-3m-2023-10.csv'
  - 'BTCUSDT-3m-2023-11.csv'
  - 'BTCUSDT-3m-2023-12.csv'
  - 'BTCUSDT-3m-2024-01.csv'
  - 'BTCUSDT-3m-2024-02.csv'
  - 'BTCUSDT-3m-2024-03.csv'
  - 'BTCUSDT-3m-2024-04.csv'
  - 'BTCUSDT-3m-2024-05.csv'
download_dir: 'data'
#data_limit: 500
target: 'Close_diff'
seq_length: 60
batch_size: 128
hidden_dim: 32
num_layers: 2
learning_rate: 0.0001
volatility_window_size: 50
num_epochs: 100

use_pca: True
use_attention: True
scaler_type: 'standard'

dropout: 0.15
weight_decay: 0.0001